# Generated by Django 2.1.1 on 2018-09-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='author',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
