# Generated by Django 2.1.1 on 2018-10-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
